Experiment charts
otavioon/librep-hiaac pull request #23
Opened 2022-09-12 13:12 UTC by alvespatrick

I created two notebooks (using 30 Hz and 20 Hz datasets) with the experiment by merging KuHar and MotionSense, and reducing dimensionality by applying t-SNE.

2022-09-12 18:46 UTC, alvespatrick commented
The tsne.py file in my branch was broken. I fixed it by copying and pasting tsne.py from master.

2022-09-13 14:32 UTC, otavioon requested changes
Hello @alvespatrick . The `librep/transforms/tsne.py` file was removed and should not be. Could you, please, add this file again?

2022-09-14 00:34 UTC, alvespatrick commented
Hello @otavioon. I've added the tsne.py. Thanks for your report.

2022-09-16 11:16 UTC, otavioon approved these changes

2022-09-16 11:16 UTC, merged